# -*- coding: utf-8 -*-
"""рпг.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134YzfiuTG-Dz9Ueo8uBy7o9MxLtN6uqj
"""

# from pygments.formatters import load_formatter_from_file
# from traitlets.config.configurable import LazyConfigValue
# # put your python code here
import random as r
hp = 0
coins = 0
damage = 0
day = 0

def PrintParametrs ():
  print("Ваши параметры: Здоровье={0}, Крышечки={1}, Наносимый урон={2}".format(hp, coins, damage), "Вы путешествуете", day ,'день....')

def initGame(initHp, initCoins, initDamage):
  global hp
  global coins
  global damage
  global day

  hp = initHp
  coins = initCoins
  damage = initDamage

  print ("Твоё путешествие начинается...")
  #PrintParametrs()

def meetShop():
  global hp
  global coins
  global damage
  def buy(cost):
    global coins
    if coins >= cost:
      coins -= cost
      return True
    else:
      print('Не хватает крышечек')
      False
  weapon = ['Дубинка ценой в 25 крышечек (2 дамага)', 'Самопал стоимостью 35 крышек (3 дамага)', 'Пистолет с ценником 45 (4 дамага)', 'Автомат за 55 крышек (5 дамага)', 'Миниган обойдётся тебе в 70 крышек (6 дамага)']
  weaponsCost = 25
  oneHPcost = 5
  threeHPcost = 12
  print('На пути тебе встретился торгаш')
  PrintParametrs()
  while input('Што буим делать? (введите 1 чтобы зайти к торгашу):') .lower() == '1':
    print('Асортимент торговца')
    print('1)Одна единица здоровья-', oneHPcost, 'крышечек')
    print('2)Тры единицы здоровья-', threeHPcost, 'крышечек')
    weaponsale = weapon[r.randint(0,4)]
    print('3)Приглядеться к', weaponsale,)

    PrintParametrs()
    choise = input("Что хочешь приобрести (введи цифру от 1 до 3)?: ")
    if choise == '1':
      if buy(oneHPcost):
        hp += 1
        PrintParametrs()
    elif choise == '2':
      if buy(threeHPcost):
        hp += 3
        PrintParametrs()
    elif choise == '3':
      if weaponsale == "Дубинка ценой в 25 крышечек (2 дамага)":
        if buy(25):
          damage = 2 
          PrintParametrs()
      if weaponsale == "Самопал стоимостью 35 крышек (3 дамага)":
        if buy(35):
          damage = 3 
          PrintParametrs()
      if weaponsale == "Пистолет с ценником 45 (4 дамага)":
        if buy(45):
          damage = 4 
          PrintParametrs()
      if weaponsale == "Автомат за 55 крышек (5 дамага)":
        if buy(55):
          damage = 5 
          PrintParametrs()
      if weaponsale == "Миниган обойдётся тебе в 70 крышек (6 дамага)":
        if buy(70):
          damage = 6 
          PrintParametrs()
    else:
      print('Моя твоя не понимать...')


def meetmonster():
  global hp
  global coins
  global damage
  global day
  lvlgame = day // 15
  monsterhp = 2 + lvlgame
  monsterdamage = 1 + lvlgame
  monsters = ['Радтараканище', 'Дикий опосум', 'Пенчекряк', 'Крепкий рейдер','Бешенный Гуль','Супермутантище']
  monster = r.choice(monsters)
  print('Ты таки нашёл приключения в виде драки! На тебя прёт {0}, у него {1} здоровья и {2} урона'.format(monster, monsterhp, monsterdamage))
  PrintParametrs()
  while monsterhp > 0:
    choise = input ('Что будем делать?!(1-атаковать / 2-попытаться сбежать!):  ')
    if choise == "1":
      monsterhp -= damage
      print('Ты всёк негодяю! У него осталось', monsterhp,"холстов!" )
    if choise == '2':
      chance = r.randint(0,1)
      if chance == 0:
        print('Тебе удалось удрать от супостата!! Здоровье ты сохранил, но честь, увы НЕТ...')
        break
      if chance == 1:
        print("Негодяй оказался таки проворней тебя, и догнав смачно ударил!")
      else:
        continue
    if monsterhp > 0:
      hp -= monsterdamage
      print(monster ,"добротно всёк тебе,  и у тебя осталось", hp,  "холстоф.")
    if hp <= 0:
      break
  else:
    loot = 10 + (1 * lvlgame)
    coins += loot
    print('Тебе удалось одержать героическую победу! После оной, ты благополучно обшарил "карманы" своего оппонента и нашёл:', loot, 'крышечек!!')
    PrintParametrs


def gameloop():  
  global day
  situation = r.randint(0,3)
  if situation == 0:
    day += 1
    print("Магазин")
    meetShop()
  elif situation == 1:
    day += 1
    meetmonster()
    input()
  else:
    PrintParametrs()
    day += 1
    print("Блуждаю....")
    input()

initGame(10,20,1)

while True:
  gameloop()
  if hp <= 0:
    if input("Потрачено... Хочешь ли ты вновь отправиться в путь? Да/Нет").lower() == "да":
      initGame(10,20,1)
    else:
      break