# -*- coding: utf-8 -*-
"""рпг.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/134YzfiuTG-Dz9Ueo8uBy7o9MxLtN6uqj
"""

# from pygments.formatters import load_formatter_from_file
# from traitlets.config.configurable import LazyConfigValue
# # put your python code here
import random as r

hp = 0
coins = 0
damage = 0
day = 0
damagefriend = 0



def PrintParametrs ():
  print("Ваши параметры: Здоровье={0}, Крышечки={1}, Наносимый урон={2}".format(hp, coins, damage + damagefriend), "Вы путешествуете", day ,'день....')

def initGame(initHp, initCoins, initDamage):
  global hp
  global coins
  global damage
  global day

  hp = initHp
  coins = initCoins
  damage = initDamage

  print ("    Война... Война никогда не меняется. Конец света наступил в полном соответствии с нашими предсказаниями. Извечная проблема - слишком много людей и слишком мало ресурсов.\n Первые ядерные взрывы, осуществленные на территории России, автоматически привели в действие проект, разработанный еще при СССР, - 'Мёртвая рука'.\n После этого, судьба всей планеты была предрешена. Ядерные ракеты.. начали лететь во все стороны из всех государств, имеющих их на своём вооружении.\n После этого планета погрузилась во тьму на сотни лет... Некоторые 'счастливчики' успели добраться до бункеров, защищающих от последствий ядерных ударов.\n Твои предки оказались в этом списке. Ты родился и вырос в подобном бункере. Получил необходимое образование и навыки для работы инженером в своём подземном городе.\n Вся твоя жизнь была стабильна и предсказуема, пока по твоей вине не произошло ЧП, выведшее из строя систему водоочистки бункера.\n Тем самым ты поставил существование всего бункера под угрозу. От неминуемой казни тебя спасла только хорошая дружба твоего отца и главы общины, а также твоя безупречная репутация.\n Вместо быстрой и лёгкой смерти, тебе выпала более тяжёлая судьба... Людям свойственно совершать ошибки и это простительно, при условии их исправления\n Тебя отправили на поверхность с банальной миссией: найти новый чип для фильтра водной очистки...\n Твоё путешествие начинается...\n\n\n\n    ")
  #PrintParametrs()

def meet34day():
  global hp
  global coins
  global damage
  global day
  global damagefriend
  PrintParametrs()
  a = 1
  while a == 1:
    choise = input('В поисках фильтра ты набрёл на истощенного пса, привязанного к довоенному дорожному знаку. Вы осторожно приблизились к бедолаге, он из последних сил потянулся к вам и лизнул вашу руку.\n Вы не можете просто оставить его в таком положении... Что вы сделаете:\n 1)Прекратите мучения, быстро прервав его жизнь. После чего разделаете его на мясо для пополнения своих запасов продовольствия. В мире после ядерной войны, проблема еды стоит очень остро...\n (Получите 15 крышечек продав шкуру в ближайшем поселении, и пополните здоровье на 10 вдоволь утолив свой голод). \n2) Напоите бедолагу и поделитесь с ним своей пищей (-5 здоровья). Неизвестно как себя поведёт пёсель после этого...\n\n')
    if choise == '1':
      hp += 10
      coins += 15
      print("Вы всё сделали быстро и безболезненно....")
      a = 0
    elif choise == '2':
      hp -=5
      damagefriend += 2
      print("Песёль быстро уплетает предложенные вами дары. После чего присоединяется к вашим приключениям, дабы помогать в схватках. (Получаете +2 к урону!)\n ")
      a = 0
    else:
      print('\n Введите цифру 1 или 2')
      a = 1

def meet100day():
  print('Поздравляю, блуждая по разрушенному континенту, ты случайно наткнулся на заброшенный завод, который производил нужные тебе чипы. Глубоко в подвале, тебе удалось найти ящик искомых чипов!\n Теперь твой подземный город будет спасён!')
    

def meetShop():
  global hp
  global coins
  global damage
  def buy(cost):
    global coins
    if coins >= cost:
      coins -= cost
      return True
    else:
      print('Не хватает крышечек')
      False
  weapon = ['Дубинка ценой в 25 крышечек (2 дамага)', 'Самопал стоимостью 35 крышек (3 дамага)', 'Пистолет с ценником 45 (4 дамага)', 'Автомат за 55 крышек (5 дамага)', 'Миниган обойдётся тебе в 70 крышек (6 дамага)']
  weaponsCost = 25
  oneHPcost = 5
  threeHPcost = 12
  print('На пути тебе встретился торгаш')
  PrintParametrs()
  while input('Што буим делать? (введите 1 чтобы зайти к торгашу, или любое другое число чтобы уйти):\n\n') .lower() == '1':
    print('Асортимент торговца')
    print('1)Одна единица здоровья-', oneHPcost, 'крышечек')
    print('2)Тры единицы здоровья-', threeHPcost, 'крышечек')
    weaponsale = weapon[r.randint(0,4)]
    print('3)Приглядеться к', weaponsale,)

    PrintParametrs()
    choise = input("Что хочешь приобрести (введи цифру от 1 до 3)?: \n\n\n")
    if choise == '1':
      if buy(oneHPcost):
        hp += 1
        PrintParametrs()
    elif choise == '2':
      if buy(threeHPcost):
        hp += 3
        PrintParametrs()
    elif choise == '3':
      if weaponsale == "Дубинка ценой в 25 крышечек (2 дамага)":
        if buy(25):
          damage = 2 
          PrintParametrs()
      if weaponsale == "Самопал стоимостью 35 крышек (3 дамага)":
        if buy(35):
          damage = 3 
          PrintParametrs()
      if weaponsale == "Пистолет с ценником 45 (4 дамага)":
        if buy(45):
          damage = 4 
          PrintParametrs()
      if weaponsale == "Автомат за 55 крышек (5 дамага)":
        if buy(55):
          damage = 5 
          PrintParametrs()
      if weaponsale == "Миниган обойдётся тебе в 70 крышек (6 дамага)":
        if buy(70):
          damage = 6 
          PrintParametrs()
    else:
      print('Моя твоя не понимать...\n\n\n')


def meetmonster():
  global hp
  global coins
  global damage
  global day
  global damagefriend
  lvlgame = day // 15
  monsterhp = 2 + lvlgame
  monsterdamage = 1 + lvlgame
  monsters = ['Радтараканище', 'Дикий опосум', 'Пенчекряк', 'Крепкий рейдер','Бешеный Гуль','Супермутантище']
  monster = r.choice(monsters)
  print('Ты таки нашёл приключения в виде драки! На тебя прёт {0}, у него {1} здоровья и {2} урона'.format(monster, monsterhp, monsterdamage))
  PrintParametrs()
  while monsterhp > 0:
    choise = input ('Что будем делать?!(1-атаковать / 2-попытаться сбежать!):  ')
    if choise == "1":
      monsterhp -= (damage + damagefriend)
      print('\nТы всёк негодяю! У него осталось', monsterhp,"холстов!" )
    if choise == '2':
      chance = r.randint(0,1)
      if chance == 0:
        print('\nТебе удалось удрать от супостата!! Здоровье ты сохранил, но честь, увы НЕТ...')
        break
      if chance == 1:
        print("\nНегодяй оказался таки проворней тебя, и догнав смачно ударил!")
      else:
        continue
    if monsterhp > 0:
      hp -= monsterdamage
      print(monster ,"добротно всёк тебе,  и у тебя осталось", hp,  "холстоф.")
    if hp <= 0:
      break
  else:
    loot = r.randint(7,10) + (2 * lvlgame)
    coins += loot
    print('\nТебе удалось одержать героическую победу! После оной, ты благополучно обшарил "карманы" своего оппонента и нашёл:', loot, 'крышечек!!')
    PrintParametrs


def gameloop():  
  global day
  global hp
  global damagefriend
  situation = r.randint(0,3)
  if day == 34:
    meet34day()

  if day == 100:
    meet100day()
    hp -= 10000

  if situation == 0:
    day += 1
    print("Магазин")
    meetShop()
  elif situation == 1:
    day += 1
    meetmonster()
    input()
  else:
    day += 1
    PrintParametrs()
    print("Блуждаю....")
    input()

initGame(10,20,1)

while True:
  gameloop()
  if hp <= 0:
    if input("Потрачено... Хочешь ли ты вновь отправиться в путь? Да/Нет").lower() == "да":
      day = 0
      damagefriend = 0
      initGame(10,20,1)

    else:
      break